2023-09-13 11:42:58,091 INFO    StreamThr :5876 [internal.py:wandb_internal():86] W&B internal server running at pid: 5876, started at: 2023-09-13 11:42:58.088451
2023-09-13 11:42:58,094 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status
2023-09-13 11:42:58,099 INFO    WriterThread:5876 [datastore.py:open_for_write():85] open: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/run-yfj11h1x.wandb
2023-09-13 11:42:58,100 DEBUG   SenderThread:5876 [sender.py:send():379] send: header
2023-09-13 11:42:58,100 DEBUG   SenderThread:5876 [sender.py:send():379] send: run
2023-09-13 11:42:58,502 INFO    SenderThread:5876 [dir_watcher.py:__init__():211] watching files in: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files
2023-09-13 11:42:58,502 INFO    SenderThread:5876 [sender.py:_start_run_threads():1121] run started: yfj11h1x with start time 1694623377.189849
2023-09-13 11:42:58,516 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: summary_record
2023-09-13 11:42:58,517 INFO    SenderThread:5876 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-13 11:42:58,540 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: check_version
2023-09-13 11:42:58,540 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: check_version
2023-09-13 11:42:58,639 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: run_start
2023-09-13 11:42:58,639 DEBUG   HandlerThread:5876 [system_info.py:__init__():31] System info init
2023-09-13 11:42:58,640 DEBUG   HandlerThread:5876 [system_info.py:__init__():46] System info init done
2023-09-13 11:42:58,640 INFO    HandlerThread:5876 [system_monitor.py:start():181] Starting system monitor
2023-09-13 11:42:58,640 INFO    SystemMonitor:5876 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-13 11:42:58,641 INFO    HandlerThread:5876 [system_monitor.py:probe():201] Collecting system info
2023-09-13 11:42:58,641 INFO    SystemMonitor:5876 [interfaces.py:start():190] Started cpu monitoring
2023-09-13 11:42:58,642 INFO    SystemMonitor:5876 [interfaces.py:start():190] Started disk monitoring
2023-09-13 11:42:58,643 INFO    SystemMonitor:5876 [interfaces.py:start():190] Started gpu monitoring
2023-09-13 11:42:58,643 INFO    SystemMonitor:5876 [interfaces.py:start():190] Started memory monitoring
2023-09-13 11:42:58,644 INFO    SystemMonitor:5876 [interfaces.py:start():190] Started network monitoring
2023-09-13 11:42:58,645 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:42:58,646 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:42:58,669 DEBUG   HandlerThread:5876 [system_info.py:probe():195] Probing system
2023-09-13 11:42:58,670 DEBUG   HandlerThread:5876 [system_info.py:_probe_git():180] Probing git
2023-09-13 11:42:58,687 DEBUG   HandlerThread:5876 [system_info.py:_probe_git():188] Probing git done
2023-09-13 11:42:58,688 DEBUG   HandlerThread:5876 [system_info.py:probe():240] Probing system done
2023-09-13 11:42:58,688 DEBUG   HandlerThread:5876 [system_monitor.py:probe():210] {'os': 'Linux-5.4.0-150-generic-x86_64-with-glibc2.10', 'python': '3.8.0', 'heartbeatAt': '2023-09-13T16:42:58.669803', 'startedAt': '2023-09-13T16:42:46.578996', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'Dual_eq_Min.ipynb', 'root': '/home/ali/outlier_project/outlier_VAE', 'git': {'remote': 'git@github.com:SMATousi/outlier_VAE.git', 'commit': '87f3e68c3fb49cb034866e1f06b16f6542c24274'}, 'email': 'mohamadali.tousi@gmail.com', 'host': 'ali-GL553VD', 'username': 'ali', 'executable': '/home/ali/anaconda3/envs/rae-project/bin/python', 'cpu_count': 4, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2100.0935, 'min': 800.0, 'max': 3800.0}, 'cpu_freq_per_core': [{'current': 2100.078, 'min': 800.0, 'max': 3800.0}, {'current': 2100.273, 'min': 800.0, 'max': 3800.0}, {'current': 2100.2, 'min': 800.0, 'max': 3800.0}, {'current': 2100.007, 'min': 800.0, 'max': 3800.0}, {'current': 2100.025, 'min': 800.0, 'max': 3800.0}, {'current': 2100.039, 'min': 800.0, 'max': 3800.0}, {'current': 2100.104, 'min': 800.0, 'max': 3800.0}, {'current': 2100.022, 'min': 800.0, 'max': 3800.0}], 'disk': {'total': 457.10711669921875, 'used': 98.27404022216797}, 'gpu': 'NVIDIA GeForce GTX 1050', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1050', 'memory_total': 4294967296}], 'memory': {'total': 15.520771026611328}}
2023-09-13 11:42:58,688 INFO    HandlerThread:5876 [system_monitor.py:probe():211] Finished collecting system info
2023-09-13 11:42:58,688 INFO    HandlerThread:5876 [system_monitor.py:probe():214] Publishing system info
2023-09-13 11:42:58,688 DEBUG   HandlerThread:5876 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-09-13 11:42:58,689 DEBUG   HandlerThread:5876 [system_info.py:_save_pip():67] Saving pip packages done
2023-09-13 11:42:58,689 DEBUG   HandlerThread:5876 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-09-13 11:42:59,503 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/conda-environment.yaml
2023-09-13 11:42:59,503 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/wandb-summary.json
2023-09-13 11:42:59,504 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/requirements.txt
2023-09-13 11:43:00,648 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:00,648 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:02,336 DEBUG   HandlerThread:5876 [system_info.py:_save_conda():86] Saving conda packages done
2023-09-13 11:43:02,337 INFO    HandlerThread:5876 [system_monitor.py:probe():216] Finished publishing system info
2023-09-13 11:43:02,338 DEBUG   SenderThread:5876 [sender.py:send():379] send: files
2023-09-13 11:43:02,338 INFO    SenderThread:5876 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2023-09-13 11:43:02,356 DEBUG   SenderThread:5876 [sender.py:send():379] send: telemetry
2023-09-13 11:43:02,374 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: stop_status
2023-09-13 11:43:02,374 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: stop_status
2023-09-13 11:43:02,503 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/conda-environment.yaml
2023-09-13 11:43:02,503 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/wandb-metadata.json
2023-09-13 11:43:02,649 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:02,753 INFO    wandb-upload_0:5876 [upload_job.py:push():131] Uploaded file /tmp/tmpwfh68jkjwandb/fjpxoryf-wandb-metadata.json
2023-09-13 11:43:02,767 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:03,503 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_created():271] file/dir created: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/output.log
2023-09-13 11:43:03,768 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:04,767 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:04,768 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:05,504 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/output.log
2023-09-13 11:43:06,769 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:06,770 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:08,769 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:08,771 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:08,771 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:10,771 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:10,771 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:12,772 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:12,772 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:13,769 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:14,773 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:14,773 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:16,775 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:16,775 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:17,355 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: stop_status
2023-09-13 11:43:17,355 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: stop_status
2023-09-13 11:43:18,776 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:18,776 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:19,544 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:20,777 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:20,778 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:22,779 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:22,780 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:24,545 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:24,782 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:24,782 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:26,783 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:26,784 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:28,853 ERROR   gpu       :5876 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2023-09-13 11:43:28,853 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:28,854 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:29,552 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:30,520 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/config.yaml
2023-09-13 11:43:30,855 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:30,855 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:32,356 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: stop_status
2023-09-13 11:43:32,357 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: stop_status
2023-09-13 11:43:32,857 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:32,857 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:34,858 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:34,859 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:35,597 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:36,860 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:36,861 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:38,862 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:38,863 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:40,598 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:40,864 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:40,865 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:42,866 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:42,867 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:44,869 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:44,869 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:45,600 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:46,871 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:46,871 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:47,356 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: stop_status
2023-09-13 11:43:47,358 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: stop_status
2023-09-13 11:43:48,873 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:48,873 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:50,874 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:50,875 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:51,549 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:52,876 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:52,877 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:54,878 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:54,878 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:56,550 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:56,879 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:56,879 ERROR   gpu       :5876 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2023-09-13 11:43:58,644 DEBUG   SystemMonitor:5876 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-13 11:43:58,645 DEBUG   SenderThread:5876 [sender.py:send():379] send: stats
2023-09-13 11:43:58,669 DEBUG   SenderThread:5876 [sender.py:send():379] send: telemetry
2023-09-13 11:43:58,670 DEBUG   SenderThread:5876 [sender.py:send():379] send: exit
2023-09-13 11:43:58,670 INFO    SenderThread:5876 [sender.py:send_exit():584] handling exit code: 0
2023-09-13 11:43:58,670 INFO    SenderThread:5876 [sender.py:send_exit():586] handling runtime: 60
2023-09-13 11:43:58,671 INFO    SenderThread:5876 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-13 11:43:58,671 INFO    SenderThread:5876 [sender.py:send_exit():592] send defer
2023-09-13 11:43:58,671 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: defer
2023-09-13 11:43:58,671 INFO    HandlerThread:5876 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-13 11:43:58,672 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: defer
2023-09-13 11:43:58,672 INFO    SenderThread:5876 [sender.py:send_request_defer():608] handle sender defer: 0
2023-09-13 11:43:58,672 INFO    SenderThread:5876 [sender.py:transition_state():612] send defer: 1
2023-09-13 11:43:58,672 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: defer
2023-09-13 11:43:58,672 INFO    HandlerThread:5876 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-13 11:43:58,672 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: defer
2023-09-13 11:43:58,672 INFO    SenderThread:5876 [sender.py:send_request_defer():608] handle sender defer: 1
2023-09-13 11:43:58,672 INFO    SenderThread:5876 [sender.py:transition_state():612] send defer: 2
2023-09-13 11:43:58,672 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: defer
2023-09-13 11:43:58,673 INFO    HandlerThread:5876 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-13 11:43:58,673 INFO    HandlerThread:5876 [system_monitor.py:finish():190] Stopping system monitor
2023-09-13 11:43:58,673 INFO    HandlerThread:5876 [interfaces.py:finish():202] Joined cpu monitor
2023-09-13 11:43:58,673 DEBUG   SystemMonitor:5876 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-13 11:43:58,673 INFO    HandlerThread:5876 [interfaces.py:finish():202] Joined disk monitor
2023-09-13 11:43:58,673 DEBUG   SystemMonitor:5876 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-13 11:43:58,726 ERROR   gpu       :5876 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2023-09-13 11:43:58,726 INFO    HandlerThread:5876 [interfaces.py:finish():202] Joined gpu monitor
2023-09-13 11:43:58,727 INFO    HandlerThread:5876 [interfaces.py:finish():202] Joined memory monitor
2023-09-13 11:43:58,727 INFO    HandlerThread:5876 [interfaces.py:finish():202] Joined network monitor
2023-09-13 11:43:58,727 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: defer
2023-09-13 11:43:58,727 INFO    SenderThread:5876 [sender.py:send_request_defer():608] handle sender defer: 2
2023-09-13 11:43:58,728 INFO    SenderThread:5876 [sender.py:transition_state():612] send defer: 3
2023-09-13 11:43:58,728 DEBUG   SenderThread:5876 [sender.py:send():379] send: stats
2023-09-13 11:43:58,728 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: defer
2023-09-13 11:43:58,728 INFO    HandlerThread:5876 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-13 11:43:58,729 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: defer
2023-09-13 11:43:58,729 INFO    SenderThread:5876 [sender.py:send_request_defer():608] handle sender defer: 3
2023-09-13 11:43:58,729 INFO    SenderThread:5876 [sender.py:transition_state():612] send defer: 4
2023-09-13 11:43:58,729 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: defer
2023-09-13 11:43:58,729 INFO    HandlerThread:5876 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-13 11:43:58,729 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: defer
2023-09-13 11:43:58,729 INFO    SenderThread:5876 [sender.py:send_request_defer():608] handle sender defer: 4
2023-09-13 11:43:58,729 INFO    SenderThread:5876 [sender.py:transition_state():612] send defer: 5
2023-09-13 11:43:58,729 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: defer
2023-09-13 11:43:58,729 INFO    HandlerThread:5876 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-13 11:43:58,730 DEBUG   SenderThread:5876 [sender.py:send():379] send: summary
2023-09-13 11:43:59,325 INFO    SenderThread:5876 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-13 11:43:59,326 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: defer
2023-09-13 11:43:59,326 INFO    SenderThread:5876 [sender.py:send_request_defer():608] handle sender defer: 5
2023-09-13 11:43:59,327 INFO    SenderThread:5876 [sender.py:transition_state():612] send defer: 6
2023-09-13 11:43:59,327 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: defer
2023-09-13 11:43:59,327 INFO    HandlerThread:5876 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-13 11:43:59,328 DEBUG   SenderThread:5876 [sender.py:send_request():406] send_request: defer
2023-09-13 11:43:59,328 INFO    SenderThread:5876 [sender.py:send_request_defer():608] handle sender defer: 6
2023-09-13 11:43:59,334 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: status_report
2023-09-13 11:43:59,410 ERROR   SenderThread:5876 [internal_api.py:execute():326] 409 response executing GraphQL.
2023-09-13 11:43:59,411 ERROR   SenderThread:5876 [internal_api.py:execute():327] {"errors":[{"message":"run tousi-team/RAE_Outlier_GA_Dual_Test_normalized/yfj11h1x was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-09-13 11:43:59,537 INFO    Thread-26 :5876 [dir_watcher.py:_on_file_modified():288] file/dir modified: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/files/wandb-summary.json
2023-09-13 11:43:59,673 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-13 11:44:00,515 ERROR   SenderThread:5876 [internal_api.py:execute():326] 409 response executing GraphQL.
2023-09-13 11:44:00,515 ERROR   SenderThread:5876 [internal_api.py:execute():327] {"errors":[{"message":"run tousi-team/RAE_Outlier_GA_Dual_Test_normalized/yfj11h1x was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-09-13 11:44:02,672 ERROR   SenderThread:5876 [internal_api.py:execute():326] 409 response executing GraphQL.
2023-09-13 11:44:02,673 ERROR   SenderThread:5876 [internal_api.py:execute():327] {"errors":[{"message":"run tousi-team/RAE_Outlier_GA_Dual_Test_normalized/yfj11h1x was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-09-13 11:44:02,673 INFO    SenderThread:5876 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 323, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-09-13 11:44:04,674 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: keepalive
2023-09-13 11:44:07,795 ERROR   SenderThread:5876 [internal_api.py:execute():326] 409 response executing GraphQL.
2023-09-13 11:44:07,795 ERROR   SenderThread:5876 [internal_api.py:execute():327] {"errors":[{"message":"run tousi-team/RAE_Outlier_GA_Dual_Test_normalized/yfj11h1x was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-09-13 11:44:09,675 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: keepalive
2023-09-13 11:44:14,678 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: keepalive
2023-09-13 11:44:16,737 ERROR   SenderThread:5876 [internal_api.py:execute():326] 409 response executing GraphQL.
2023-09-13 11:44:16,737 ERROR   SenderThread:5876 [internal_api.py:execute():327] {"errors":[{"message":"run tousi-team/RAE_Outlier_GA_Dual_Test_normalized/yfj11h1x was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-09-13 11:44:19,679 DEBUG   HandlerThread:5876 [handler.py:handle_request():144] handle_request: keepalive
2023-09-13 11:44:35,407 ERROR   SenderThread:5876 [internal_api.py:execute():326] 409 response executing GraphQL.
2023-09-13 11:44:35,408 ERROR   SenderThread:5876 [internal_api.py:execute():327] {"errors":[{"message":"run tousi-team/RAE_Outlier_GA_Dual_Test_normalized/yfj11h1x was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-09-13 11:45:10,625 ERROR   SenderThread:5876 [internal_api.py:execute():326] 409 response executing GraphQL.
2023-09-13 11:45:10,625 ERROR   SenderThread:5876 [internal_api.py:execute():327] {"errors":[{"message":"run tousi-team/RAE_Outlier_GA_Dual_Test_normalized/yfj11h1x was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-09-13 11:45:55,286 WARNING StreamThr :5876 [internal.py:is_dead():414] Internal process exiting, parent pid 5318 disappeared
2023-09-13 11:45:55,286 ERROR   StreamThr :5876 [internal.py:wandb_internal():152] Internal process shutdown.
2023-09-13 11:45:55,701 INFO    WriterThread:5876 [datastore.py:close():294] close: /home/ali/outlier_project/outlier_VAE/wandb/run-20230913_114246-yfj11h1x/run-yfj11h1x.wandb
2023-09-13 11:45:55,701 INFO    HandlerThread:5876 [handler.py:finish():861] shutting down handler
2023-09-13 11:46:19,969 ERROR   SenderThread:5876 [internal_api.py:execute():326] 409 response executing GraphQL.
2023-09-13 11:46:19,969 ERROR   SenderThread:5876 [internal_api.py:execute():327] {"errors":[{"message":"run tousi-team/RAE_Outlier_GA_Dual_Test_normalized/yfj11h1x was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-09-13 11:46:19,969 ERROR   StreamThr :5876 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 323, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1958, in upsert_run
    response = self.gql(
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 295, in gql
    ret = self._retry_gql(
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 329, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/click/utils.py", line 319, in echo
    file.flush()
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_util.py", line 100, in _run
    self._process(record)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal.py", line 328, in _process
    self._sm.send(record)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 386, in send
    send_handler(record)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 408, in send_request
    send_handler(record)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 634, in send_request_defer
    self.debounce(final=True)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 537, in debounce
    self._maybe_update_config(always=final)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 514, in _maybe_update_config
    self._debounce_config()
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/sender.py", line 543, in _debounce_config
    self._api.upsert_run(
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/apis/normalize.py", line 87, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 1958, in upsert_run
    response = self.gql(
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 295, in gql
    ret = self._retry_gql(
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 329, in execute
    wandb.termerror(f"Error while calling W&B API: {error} ({response})")
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/errors/term.py", line 61, in termerror
    _log(
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/wandb/errors/term.py", line 95, in _log
    click.echo(line, file=sys.stderr, nl=newline)
  File "/home/ali/anaconda3/envs/rae-project/lib/python3.8/site-packages/click/utils.py", line 319, in echo
    file.flush()
wandb.errors.CommError: [Errno 32] Broken pipe
2023-09-13 11:46:21,315 INFO    MainThread:5876 [internal.py:handle_exit():76] Internal process exited
2023-09-13 11:46:21,315 INFO    MainThread:5876 [internal.py:handle_exit():76] Internal process exited
