2023-06-23 15:45:26,260 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-23 15:45:26,261 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Configure stats pid to 443684
2023-06-23 15:45:26,261 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from /home/macula/SMATousi/.config/wandb/settings
2023-06-23 15:45:26,261 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/settings
2023-06-23 15:45:26,261 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-23 15:45:26,261 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-23 15:45:26,261 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-23 15:45:26,261 INFO    MainThread:443684 [wandb_init.py:_log_setup():507] Logging user logs to /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/run-20230623_154518-1cp5mu8v/logs/debug.log
2023-06-23 15:45:26,262 INFO    MainThread:443684 [wandb_init.py:_log_setup():508] Logging internal logs to /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/run-20230623_154518-1cp5mu8v/logs/debug-internal.log
2023-06-23 15:45:26,262 INFO    MainThread:443684 [wandb_init.py:init():547] calling init triggers
2023-06-23 15:45:26,262 INFO    MainThread:443684 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {}
2023-06-23 15:45:26,262 INFO    MainThread:443684 [wandb_init.py:init():572] re-initializing run, found existing run on stack: 14jwx4h4
2023-06-23 15:45:26,267 INFO    MainThread:443684 [wandb_run.py:_finish():1890] finishing run tousi-team/VAE_Outlier_GA_With_Penalty/14jwx4h4
2023-06-23 15:45:26,268 INFO    MainThread:443684 [jupyter.py:save_history():445] not saving jupyter history
2023-06-23 15:45:26,268 INFO    MainThread:443684 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-06-23 15:45:26,268 INFO    MainThread:443684 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-06-23 15:45:26,268 INFO    MainThread:443684 [wandb_run.py:_atexit_cleanup():2124] got exitcode: 0
2023-06-23 15:45:26,269 INFO    MainThread:443684 [wandb_run.py:_restore():2107] restore
2023-06-23 15:45:26,269 INFO    MainThread:443684 [wandb_run.py:_restore():2113] restore done
2023-06-23 15:46:05,496 INFO    MainThread:443684 [wandb_init.py:init():596] starting backend
2023-06-23 15:46:05,497 INFO    MainThread:443684 [wandb_init.py:init():600] setting up manager
2023-06-23 15:46:05,501 INFO    MainThread:443684 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-23 15:46:05,502 INFO    MainThread:443684 [wandb_init.py:init():606] backend started and connected
2023-06-23 15:46:05,515 INFO    MainThread:443684 [wandb_run.py:_label_probe_notebook():1235] probe notebook
2023-06-23 15:46:05,519 INFO    MainThread:443684 [wandb_init.py:init():703] updated telemetry
2023-06-23 15:46:05,684 INFO    MainThread:443684 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-23 15:47:05,766 ERROR   MainThread:443684 [wandb_init.py:init():762] encountered error: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-06-23 15:47:05,979 ERROR   MainThread:443684 [wandb_init.py:init():1170] Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 768, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 60.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-06-23 15:47:24,391 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-23 15:47:24,392 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Configure stats pid to 443684
2023-06-23 15:47:24,392 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from /home/macula/SMATousi/.config/wandb/settings
2023-06-23 15:47:24,392 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/settings
2023-06-23 15:47:24,392 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-23 15:47:24,392 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-23 15:47:24,392 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-23 15:47:24,393 INFO    MainThread:443684 [wandb_init.py:_log_setup():507] Logging user logs to /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/run-20230623_154723-xhoyohrp/logs/debug.log
2023-06-23 15:47:24,393 INFO    MainThread:443684 [wandb_init.py:_log_setup():508] Logging internal logs to /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/run-20230623_154723-xhoyohrp/logs/debug-internal.log
2023-06-23 15:47:24,393 INFO    MainThread:443684 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f529b1da690>
2023-06-23 15:47:24,393 INFO    MainThread:443684 [wandb_init.py:init():547] calling init triggers
2023-06-23 15:47:24,394 INFO    MainThread:443684 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {}
2023-06-23 15:47:24,394 INFO    MainThread:443684 [wandb_init.py:init():596] starting backend
2023-06-23 15:47:24,394 INFO    MainThread:443684 [wandb_init.py:init():600] setting up manager
2023-06-23 15:47:24,398 INFO    MainThread:443684 [backend.py:_multiprocessing_setup():108] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-06-23 15:47:24,400 INFO    MainThread:443684 [wandb_init.py:init():606] backend started and connected
2023-06-23 15:47:24,411 INFO    MainThread:443684 [wandb_run.py:_label_probe_notebook():1235] probe notebook
2023-06-23 15:47:24,415 INFO    MainThread:443684 [wandb_init.py:init():703] updated telemetry
2023-06-23 15:47:24,658 INFO    MainThread:443684 [wandb_init.py:init():736] communicating run to backend with 60.0 second timeout
2023-06-23 15:47:54,296 WARNING MsgRouterThr:443684 [router.py:message_loop():77] message_loop has been closed
2023-06-23 15:47:54,297 WARNING MsgRouterThr:443684 [router.py:message_loop():77] message_loop has been closed
2023-06-23 15:47:54,297 WARNING MsgRouterThr:443684 [router.py:message_loop():77] message_loop has been closed
2023-06-23 15:47:54,757 ERROR   MainThread:443684 [wandb_init.py:init():1170] transport failed
Traceback (most recent call last):
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 742, in init
    cancel=True,
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/mailbox.py", line 281, in wait
    raise MailboxError("transport failed")
wandb.sdk.lib.mailbox.MailboxError: transport failed
2023-06-23 15:48:32,583 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-23 15:48:32,585 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Configure stats pid to 443684
2023-06-23 15:48:32,585 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from /home/macula/SMATousi/.config/wandb/settings
2023-06-23 15:48:32,585 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/settings
2023-06-23 15:48:32,585 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-23 15:48:32,585 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-23 15:48:32,585 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-23 15:48:32,586 INFO    MainThread:443684 [wandb_init.py:_log_setup():507] Logging user logs to /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/run-20230623_154830-1hrszbcp/logs/debug.log
2023-06-23 15:48:32,586 INFO    MainThread:443684 [wandb_init.py:_log_setup():508] Logging internal logs to /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/run-20230623_154830-1hrszbcp/logs/debug-internal.log
2023-06-23 15:48:32,586 INFO    MainThread:443684 [wandb_init.py:init():547] calling init triggers
2023-06-23 15:48:32,586 INFO    MainThread:443684 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {}
2023-06-23 15:48:32,586 INFO    MainThread:443684 [wandb_init.py:init():596] starting backend
2023-06-23 15:48:32,586 INFO    MainThread:443684 [wandb_init.py:init():600] setting up manager
2023-06-23 15:48:32,658 ERROR   MainThread:443684 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2023-06-23 15:48:51,444 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Current SDK version is 0.15.4
2023-06-23 15:48:51,445 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Configure stats pid to 443684
2023-06-23 15:48:51,445 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from /home/macula/SMATousi/.config/wandb/settings
2023-06-23 15:48:51,446 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/settings
2023-06-23 15:48:51,446 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-06-23 15:48:51,446 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-06-23 15:48:51,446 INFO    MainThread:443684 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-06-23 15:48:51,446 INFO    MainThread:443684 [wandb_init.py:_log_setup():507] Logging user logs to /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/run-20230623_154845-3w3vem94/logs/debug.log
2023-06-23 15:48:51,446 INFO    MainThread:443684 [wandb_init.py:_log_setup():508] Logging internal logs to /home/macula/SMATousi/VAE_outlier/outlier_VAE/wandb/run-20230623_154845-3w3vem94/logs/debug-internal.log
2023-06-23 15:48:51,447 INFO    MainThread:443684 [wandb_init.py:init():547] calling init triggers
2023-06-23 15:48:51,447 INFO    MainThread:443684 [wandb_init.py:init():555] wandb.init called with sweep_config: {}
config: {}
2023-06-23 15:48:51,447 INFO    MainThread:443684 [wandb_init.py:init():596] starting backend
2023-06-23 15:48:51,447 INFO    MainThread:443684 [wandb_init.py:init():600] setting up manager
2023-06-23 15:48:51,495 ERROR   MainThread:443684 [wandb_init.py:init():1180] error
Traceback (most recent call last):
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 1152, in init
    run = wi.init()
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 601, in init
    manager._inform_init(settings=self.settings, run_id=self.settings.run_id)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/wandb_manager.py", line 208, in _inform_init
    svc_iface._svc_inform_init(settings=settings, run_id=run_id)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/service/service_sock.py", line 38, in _svc_inform_init
    self._sock_client.send(inform_init=inform_init)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 211, in send
    self.send_server_request(server_req)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/macula/SMATousi/.conda/envs/mac-deep/lib/python3.7/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
